-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 13:45:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencia` DEFAULT CHARACTER SET utf8 ;
USE `asistencia` ;

-- -----------------------------------------------------
-- Table `asistencia`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`responsable` (
  `pk_responsable` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_responsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`RegistroCharros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`acceso` (
  `pk_acceso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `tipo_acceso` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_responsable` INT NOT NULL,
  PRIMARY KEY (`pk_accesos`),
  INDEX `fk_accesos_responsable_idx` (`fk_responsable` ASC),
  CONSTRAINT `fk_accesos_responsable`
    FOREIGN KEY (`fk_responsable`)
    REFERENCES `asistencia`.`responsable` (`pk_responsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'acceso'@'localhost' IDENTIFIED BY '#corpoteg#7777#';

GRANT ALL PRIVILEGES ON asistencia.* TO 'asistencia'@'localhost';

FLUSH PRIVILEGES;